# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opensw_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1456, 1216)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 10, 1411, 1204))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.url_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_text.sizePolicy().hasHeightForWidth())
        self.url_text.setSizePolicy(sizePolicy)
        self.url_text.setMinimumSize(QtCore.QSize(0, 0))
        self.url_text.setMaximumSize(QtCore.QSize(1250, 25))
        self.url_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_text.setObjectName("url_text")
        self.gridLayout.addWidget(self.url_text, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.send_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_4.addWidget(self.send_button)
        self.clear_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_4.addWidget(self.clear_button)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.result_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.result_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.result_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.result_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.result_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.result_menu.setAcceptRichText(True)
        self.result_menu.setObjectName("result_menu")
        self.gridLayout.addWidget(self.result_menu, 4, 0, 1, 1)
        self.header_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.header_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.header_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.header_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.header_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_menu.setAcceptRichText(True)
        self.header_menu.setObjectName("header_menu")
        self.gridLayout.addWidget(self.header_menu, 0, 0, 1, 1)
        self.header_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_text.sizePolicy().hasHeightForWidth())
        self.header_text.setSizePolicy(sizePolicy)
        self.header_text.setMinimumSize(QtCore.QSize(0, 0))
        self.header_text.setMaximumSize(QtCore.QSize(1250, 80))
        self.header_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_text.setObjectName("header_text")
        self.gridLayout.addWidget(self.header_text, 0, 1, 1, 1)
        self.parameter_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.parameter_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.parameter_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.parameter_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.parameter_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parameter_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parameter_menu.setAcceptRichText(True)
        self.parameter_menu.setObjectName("parameter_menu")
        self.gridLayout.addWidget(self.parameter_menu, 3, 0, 1, 1)
        self.parameter_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_text.sizePolicy().hasHeightForWidth())
        self.parameter_text.setSizePolicy(sizePolicy)
        self.parameter_text.setMinimumSize(QtCore.QSize(0, 0))
        self.parameter_text.setMaximumSize(QtCore.QSize(1250, 80))
        self.parameter_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parameter_text.setObjectName("parameter_text")
        self.gridLayout.addWidget(self.parameter_text, 3, 1, 1, 1)
        self.url_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.url_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.url_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.url_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.url_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_menu.setAcceptRichText(True)
        self.url_menu.setObjectName("url_menu")
        self.gridLayout.addWidget(self.url_menu, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setKerning(False)
        self.groupBox.setFont(font)
        self.groupBox.setMouseTracking(False)
        self.groupBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.get_radiobutton = QtWidgets.QRadioButton(self.groupBox)
        self.get_radiobutton.setGeometry(QtCore.QRect(0, 4, 48, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_radiobutton.sizePolicy().hasHeightForWidth())
        self.get_radiobutton.setSizePolicy(sizePolicy)
        self.get_radiobutton.setObjectName("get_radiobutton")
        self.post_radiobutton = QtWidgets.QRadioButton(self.groupBox)
        self.post_radiobutton.setGeometry(QtCore.QRect(60, 4, 56, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.post_radiobutton.sizePolicy().hasHeightForWidth())
        self.post_radiobutton.setSizePolicy(sizePolicy)
        self.post_radiobutton.setObjectName("post_radiobutton")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(1400, 25))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.csv_radio_button = QtWidgets.QRadioButton(self.groupBox_2)
        self.csv_radio_button.setGeometry(QtCore.QRect(610, 5, 150, 16))
        self.csv_radio_button.setMinimumSize(QtCore.QSize(150, 0))
        self.csv_radio_button.setObjectName("csv_radio_button")
        self.html_radio_button = QtWidgets.QRadioButton(self.groupBox_2)
        self.html_radio_button.setGeometry(QtCore.QRect(460, 5, 150, 16))
        self.html_radio_button.setMinimumSize(QtCore.QSize(150, 0))
        self.html_radio_button.setObjectName("html_radio_button")
        self.xml_radio_button = QtWidgets.QRadioButton(self.groupBox_2)
        self.xml_radio_button.setGeometry(QtCore.QRect(310, 5, 150, 16))
        self.xml_radio_button.setMinimumSize(QtCore.QSize(150, 0))
        self.xml_radio_button.setObjectName("xml_radio_button")
        self.json_radio_button = QtWidgets.QRadioButton(self.groupBox_2)
        self.json_radio_button.setGeometry(QtCore.QRect(160, 5, 150, 16))
        self.json_radio_button.setMinimumSize(QtCore.QSize(150, 0))
        self.json_radio_button.setObjectName("json_radio_button")
        self.text_radio_button = QtWidgets.QRadioButton(self.groupBox_2)
        self.text_radio_button.setGeometry(QtCore.QRect(10, 5, 150, 16))
        self.text_radio_button.setMinimumSize(QtCore.QSize(150, 0))
        self.text_radio_button.setObjectName("text_radio_button")
        self.download_button = QtWidgets.QPushButton(self.groupBox_2)
        self.download_button.setGeometry(QtCore.QRect(1290, 0, 101, 23))
        self.download_button.setObjectName("download_button")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.csv_array_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.csv_array_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.csv_array_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.csv_array_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.csv_array_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_menu.setAcceptRichText(True)
        self.csv_array_menu.setObjectName("csv_array_menu")
        self.horizontalLayout.addWidget(self.csv_array_menu)
        self.csv_array_1 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_array_1.sizePolicy().hasHeightForWidth())
        self.csv_array_1.setSizePolicy(sizePolicy)
        self.csv_array_1.setMinimumSize(QtCore.QSize(0, 0))
        self.csv_array_1.setMaximumSize(QtCore.QSize(1250, 25))
        self.csv_array_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_1.setObjectName("csv_array_1")
        self.horizontalLayout.addWidget(self.csv_array_1)
        self.csv_array_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_array_2.sizePolicy().hasHeightForWidth())
        self.csv_array_2.setSizePolicy(sizePolicy)
        self.csv_array_2.setMinimumSize(QtCore.QSize(0, 0))
        self.csv_array_2.setMaximumSize(QtCore.QSize(1250, 25))
        self.csv_array_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_2.setObjectName("csv_array_2")
        self.horizontalLayout.addWidget(self.csv_array_2)
        self.csv_array_3 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_array_3.sizePolicy().hasHeightForWidth())
        self.csv_array_3.setSizePolicy(sizePolicy)
        self.csv_array_3.setMinimumSize(QtCore.QSize(0, 0))
        self.csv_array_3.setMaximumSize(QtCore.QSize(1250, 25))
        self.csv_array_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_3.setObjectName("csv_array_3")
        self.horizontalLayout.addWidget(self.csv_array_3)
        self.csv_array_4 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_array_4.sizePolicy().hasHeightForWidth())
        self.csv_array_4.setSizePolicy(sizePolicy)
        self.csv_array_4.setMinimumSize(QtCore.QSize(0, 0))
        self.csv_array_4.setMaximumSize(QtCore.QSize(1250, 25))
        self.csv_array_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_4.setObjectName("csv_array_4")
        self.horizontalLayout.addWidget(self.csv_array_4)
        self.csv_array_5 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_array_5.sizePolicy().hasHeightForWidth())
        self.csv_array_5.setSizePolicy(sizePolicy)
        self.csv_array_5.setMinimumSize(QtCore.QSize(0, 0))
        self.csv_array_5.setMaximumSize(QtCore.QSize(1250, 25))
        self.csv_array_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.csv_array_5.setObjectName("csv_array_5")
        self.horizontalLayout.addWidget(self.csv_array_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.result_json = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_json.sizePolicy().hasHeightForWidth())
        self.result_json.setSizePolicy(sizePolicy)














        self.result_json.setMinimumSize(QtCore.QSize(0, 650))
        self.result_json.setMaximumSize(QtCore.QSize(700, 700))
        self.result_json.setSizeIncrement(QtCore.QSize(0, 1400))
        self.result_json.setBaseSize(QtCore.QSize(0, 500))
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        self.result_json.setObjectName("result_json")
        self.horizontalLayout_2.addWidget(self.result_json, 0, QtCore.Qt.AlignTop)
        # self.result_csv = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)

        self.result_csv = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_csv.sizePolicy().hasHeightForWidth())
        self.result_csv.setSizePolicy(sizePolicy)











        self.result_csv.setMinimumSize(QtCore.QSize(0, 650))
        self.result_csv.setMaximumSize(QtCore.QSize(700, 700))
        self.result_csv.setSizeIncrement(QtCore.QSize(0, 1400))
        self.result_csv.setBaseSize(QtCore.QSize(0, 500))
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        self.result_csv.setObjectName("result_csv")
        self.horizontalLayout_2.addWidget(self.result_csv, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1456, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.url_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.result_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Result</span></p></body></html>"))
        self.header_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Header</span></p></body></html>"))
        self.header_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.header_text.setPlaceholderText(_translate("MainWindow", "header1 = value1\nheader2 = value2\nheader3 = value3"))
        self.parameter_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Parameter</span></p></body></html>"))
        self.parameter_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.parameter_text.setPlaceholderText(_translate("MainWindow", "key1=value1, key2=value2, key3=value3"))
        self.url_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">URL</span></p></body></html>"))
        self.get_radiobutton.setText(_translate("MainWindow", "GET"))
        self.post_radiobutton.setText(_translate("MainWindow", "POST"))
        self.csv_radio_button.setText(_translate("MainWindow", "csv"))
        self.html_radio_button.setText(_translate("MainWindow", "html"))
        self.xml_radio_button.setText(_translate("MainWindow", "xml"))
        self.json_radio_button.setText(_translate("MainWindow", "json"))
        self.text_radio_button.setText(_translate("MainWindow", "text"))
        self.download_button.setText(_translate("MainWindow", "Downloads"))
        self.csv_array_menu.setMarkdown(_translate("MainWindow", "CSV ARRAY\n"))

        self.csv_array_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CSV ARRAY</p></body></html>"))
        self.csv_array_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.csv_array_1.setPlaceholderText(_translate("MainWindow", "response"))
        self.csv_array_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.csv_array_2.setPlaceholderText(_translate("MainWindow", "body"))
        self.csv_array_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.csv_array_3.setPlaceholderText(_translate("MainWindow", "items"))
        self.csv_array_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.csv_array_4.setPlaceholderText(_translate("MainWindow", "item"))
        self.csv_array_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.csv_array_5.setPlaceholderText(_translate("MainWindow", "etc"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
