# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opensw_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1452, 1216)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 1411, 1131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.parameter_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_text.sizePolicy().hasHeightForWidth())
        self.parameter_text.setSizePolicy(sizePolicy)
        self.parameter_text.setMinimumSize(QtCore.QSize(0, 0))
        self.parameter_text.setMaximumSize(QtCore.QSize(1250, 80))
        self.parameter_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parameter_text.setObjectName("parameter_text")
        self.gridLayout.addWidget(self.parameter_text, 4, 1, 1, 1)
        self.url_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.url_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.url_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.url_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.url_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_menu.setAcceptRichText(True)
        self.url_menu.setObjectName("url_menu")
        self.gridLayout.addWidget(self.url_menu, 3, 0, 1, 1)
        self.parameter_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.parameter_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.parameter_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.parameter_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.parameter_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parameter_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parameter_menu.setAcceptRichText(True)
        self.parameter_menu.setObjectName("parameter_menu")
        self.gridLayout.addWidget(self.parameter_menu, 4, 0, 1, 1)
        self.vertification_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertification_text.sizePolicy().hasHeightForWidth())
        self.vertification_text.setSizePolicy(sizePolicy)
        self.vertification_text.setMinimumSize(QtCore.QSize(0, 0))
        self.vertification_text.setMaximumSize(QtCore.QSize(1250, 25))
        self.vertification_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vertification_text.setObjectName("vertification_text")
        self.gridLayout.addWidget(self.vertification_text, 0, 1, 1, 1)
        self.result_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.result_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.result_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.result_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.result_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.result_menu.setAcceptRichText(True)
        self.result_menu.setObjectName("result_menu")
        self.gridLayout.addWidget(self.result_menu, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.get_radiobutton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_radiobutton.sizePolicy().hasHeightForWidth())
        self.get_radiobutton.setSizePolicy(sizePolicy)
        self.get_radiobutton.setObjectName("get_radiobutton")
        self.horizontalLayout.addWidget(self.get_radiobutton)
        self.post_radiobutton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.post_radiobutton.sizePolicy().hasHeightForWidth())
        self.post_radiobutton.setSizePolicy(sizePolicy)
        self.post_radiobutton.setObjectName("post_radiobutton")
        self.horizontalLayout.addWidget(self.post_radiobutton)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.vertification_key_check_box = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.vertification_key_check_box.setMaximumSize(QtCore.QSize(150, 16777215))
        self.vertification_key_check_box.setObjectName("vertification_key_check_box")
        self.gridLayout.addWidget(self.vertification_key_check_box, 0, 0, 1, 1)
        self.send_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.send_button.setObjectName("send_button")
        self.gridLayout.addWidget(self.send_button, 5, 1, 1, 1)
        self.url_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_text.sizePolicy().hasHeightForWidth())
        self.url_text.setSizePolicy(sizePolicy)
        self.url_text.setMinimumSize(QtCore.QSize(0, 0))
        self.url_text.setMaximumSize(QtCore.QSize(1250, 25))
        self.url_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_text.setObjectName("url_text")
        self.gridLayout.addWidget(self.url_text, 3, 1, 1, 1)
        self.header_menu = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.header_menu.setMaximumSize(QtCore.QSize(100, 25))
        self.header_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.header_menu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.header_menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_menu.setAcceptRichText(True)
        self.header_menu.setObjectName("header_menu")
        self.gridLayout.addWidget(self.header_menu, 1, 0, 1, 1)
        self.header_text = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_text.sizePolicy().hasHeightForWidth())
        self.header_text.setSizePolicy(sizePolicy)
        self.header_text.setMinimumSize(QtCore.QSize(0, 0))
        self.header_text.setMaximumSize(QtCore.QSize(1250, 80))
        self.header_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.header_text.setObjectName("header_text")
        self.gridLayout.addWidget(self.header_text, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.result_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_text.sizePolicy().hasHeightForWidth())
        self.result_text.setSizePolicy(sizePolicy)
        self.result_text.setMinimumSize(QtCore.QSize(0, 850))
        self.result_text.setMaximumSize(QtCore.QSize(1400, 1500))
        self.result_text.setSizeIncrement(QtCore.QSize(0, 1400))
        self.result_text.setBaseSize(QtCore.QSize(0, 1400))
        self.result_text.setObjectName("result_text")
        self.verticalLayout_2.addWidget(self.result_text)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1452, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.parameter_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.parameter_text.setPlaceholderText(_translate("MainWindow", "key1=value1\nkey2=value2\nkey3=value3"))
        self.url_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">URL</span></p></body></html>"))
        self.parameter_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Parameter</span></p></body></html>"))
        self.vertification_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.result_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Result</span></p></body></html>"))
        self.get_radiobutton.setText(_translate("MainWindow", "GET"))
        self.post_radiobutton.setText(_translate("MainWindow", "POST"))
        self.vertification_key_check_box.setText(_translate("MainWindow", "Vertification Key"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.url_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.header_menu.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Header</span></p></body></html>"))
        self.header_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.header_text.setPlaceholderText(_translate("MainWindow", "header1=value1\nheader2=value2\nheader3=value3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
